name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Ensure configs directory exists
      run: mkdir -p echolib/models/configs/

    - name: Create mock tokens.json
      env:
        HF_TOKEN_1: ${{ secrets.HF_TOKEN_1 }}
        HF_TOKEN_2: ${{ secrets.HF_TOKEN_2 }}
        HF_TOKEN_3: ${{ secrets.HF_TOKEN_3 }}
      run: |
        echo '[
          {
            "id": 1,
            "name": "Token1",
            "value": "'"$HF_TOKEN_1"'"
          },
          {
            "id": 2,
            "name": "Token2",
            "value": "'"$HF_TOKEN_2"'"
          },
          {
            "id": 3,
            "name": "Token3",
            "value": "'"$HF_TOKEN_3"'"
          }
        ]' > echolib/models/configs/tokens.json

    - name: Build the distribution
      run: |
        python -m pip install build
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install twine
        twine upload dist/*  
