name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ensure configs directory exists
        run: mkdir -p echolib/models/configs/

      - name: Install the package in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Create mock tokens.json
        env:
          HF_TOKEN_1: ${{ secrets.HF_TOKEN_1 }}
          HF_TOKEN_2: ${{ secrets.HF_TOKEN_2 }}
          HF_TOKEN_3: ${{ secrets.HF_TOKEN_3 }}
        run: |
          echo '[
            {
              "id": 1,
              "name": "Token1",
              "value": "'"$HF_TOKEN_1"'"
            },
            {
              "id": 2,
              "name": "Token2",
              "value": "'"$HF_TOKEN_2"'"
            },
            {
              "id": 3,
              "name": "Token3",
              "value": "'"$HF_TOKEN_3"'"
            }
          ]' > echolib/models/configs/tokens.json

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest
